# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # Specifies NuGet for .NET projects
    directory: "/" # Root directory where .csproj files exist
    schedule:
      interval: "weekly" # Dependabot checks for updates every week
    open-pull-requests-limit: 5 # Maximum 5 PRs at a time
    reviewers:
      - "ayushpatel942" # Assign PRs to a specific GitHub user
    labels:
      - "dependencies" # Labels for PRs
    ignore:
      - dependency-name: "Microsoft.EntityFrameworkCore" # Ignore updates for this dependency
    automerged_updates:
    - match:
        dependency_type: "production"
        update_type: "minor"

